


CREATE TABLE certificate_mints(faction VARCHAR, x VARCHAR, y VARCHAR, asset_mint VARCHAR, cargo_type VARCHAR);
CREATE TABLE galactic_mints(asset_mint VARCHAR, cargo_type VARCHAR);
CREATE TABLE orders(account VARCHAR, order_initializer VARCHAR, asset_mint VARCHAR, order_side VARCHAR, price BIGINT, order_origination_qty BIGINT, order_remaining_qty BIGINT, created_at BIGINT);

CREATE VIEW v_mud_buy_orders AS SELECT o.account, o.order_initializer, c.x, c.y, c.cargo_type, o.price, (o.price / 100000000) AS atlas_per_unit, o.order_origination_qty, o.order_remaining_qty, ((o.price * o.order_remaining_qty) / 100000000) AS atlas_total_value, o.created_at FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) WHERE ((c.faction = 'MUD') AND (o.order_side = 'Buy'));
CREATE VIEW v_mud_sell_orders AS SELECT o.account, o.order_initializer, c.x, c.y, c.cargo_type, o.price, (o.price / 100000000) AS atlas_per_unit, o.order_origination_qty, o.order_remaining_qty, ((o.price * o.order_remaining_qty) / 100000000) AS atlas_total_value, o.created_at FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) WHERE ((c.faction = 'MUD') AND (o.order_side = 'Sell'));
CREATE VIEW v_oni_buy_orders AS SELECT o.account, o.order_initializer, c.x, c.y, c.cargo_type, o.price, (o.price / 100000000) AS atlas_per_unit, o.order_origination_qty, o.order_remaining_qty, ((o.price * o.order_remaining_qty) / 100000000) AS atlas_total_value, o.created_at FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) WHERE ((c.faction = 'ONI') AND (o.order_side = 'Buy'));
CREATE VIEW v_oni_sell_orders AS SELECT o.account, o.order_initializer, c.x, c.y, c.cargo_type, o.price, (o.price / 100000000) AS atlas_per_unit, o.order_origination_qty, o.order_remaining_qty, ((o.price * o.order_remaining_qty) / 100000000) AS atlas_total_value, o.created_at FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) WHERE ((c.faction = 'ONI') AND (o.order_side = 'Sell'));
CREATE VIEW v_overall AS WITH overall_mean AS (SELECT c.cargo_type, o.order_side, mean(o.price) AS overall_mean_price, mean(o.order_remaining_qty) AS overall_mean_remaining_qty, sum(o.order_remaining_qty) AS overall_sum_remaining_qty FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) GROUP BY c.cargo_type, o.order_side)SELECT c.faction, c.cargo_type, o.order_side, count_star() AS count, CAST(min(o.price) AS BIGINT) AS min_price, CAST(max(o.price) AS BIGINT) AS max_price, CAST(mean(o.price) AS BIGINT) AS mean_price, CAST(overall_mean.overall_mean_price AS BIGINT) AS overall_mean_price, (((mean(o.price) - overall_mean.overall_mean_price) / overall_mean.overall_mean_price) * 100) AS percent_difference_price, CAST(min(o.order_remaining_qty) AS BIGINT) AS min_remaining_qty, CAST(max(o.order_remaining_qty) AS BIGINT) AS max_remaining_qty, CAST(mean(o.order_remaining_qty) AS BIGINT) AS mean_remaining_qty, CAST(overall_mean.overall_mean_remaining_qty AS BIGINT) AS overall_mean_remaining_qty, (((mean(o.order_remaining_qty) - overall_mean.overall_mean_remaining_qty) / overall_mean.overall_mean_remaining_qty) * 100) AS percent_difference_remaining_qty, sum(o.order_remaining_qty) AS sum_remaining_qty, overall_mean.overall_sum_remaining_qty FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) INNER JOIN overall_mean ON (((c.cargo_type = overall_mean.cargo_type) AND (o.order_side = overall_mean.order_side))) GROUP BY c.faction, c.cargo_type, o.order_side, overall_mean.overall_mean_price, overall_mean.overall_mean_remaining_qty, overall_mean.overall_sum_remaining_qty ORDER BY count DESC;
CREATE VIEW v_ustur_buy_orders AS SELECT o.account, o.order_initializer, c.x, c.y, c.cargo_type, o.price, (o.price / 100000000) AS atlas_per_unit, o.order_origination_qty, o.order_remaining_qty, ((o.price * o.order_remaining_qty) / 100000000) AS atlas_total_value, o.created_at FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) WHERE ((c.faction = 'Ustur') AND (o.order_side = 'Buy'));
CREATE VIEW v_ustur_sell_orders AS SELECT o.account, o.order_initializer, c.x, c.y, c.cargo_type, o.price, (o.price / 100000000) AS atlas_per_unit, o.order_origination_qty, o.order_remaining_qty, ((o.price * o.order_remaining_qty) / 100000000) AS atlas_total_value, o.created_at FROM orders AS o INNER JOIN certificate_mints AS c ON ((o.asset_mint = c.asset_mint)) WHERE ((c.faction = 'Ustur') AND (o.order_side = 'Sell'));



