[workspace]
resolver = "2"

members = [
    "bots/*",
    "clis/*", "crew/crew-utils",
    "galaxy",
    "program-sdks/*",
    "programs/*",
    "utils/*",
]

exclude = [
    "_archived", "crates", "crew"
]
