[workspace]
resolver = "2"

members = [
    # "apis-data/*",
    "bots/*",
    "clis/*",
    "galaxy", "markets/marketplace-slint-ui",
    "program-sdks/*",
    "programs/*",
    "utils/*",
]

exclude = [
    "_archived", "apis-data", "crates",
]
