[package]
name = "crew-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = "0.30"
anchor-lang = "0.30"
anyhow = "1.0"
mpl-bubblegum = "1.4"
mpl-token-metadata = "4.1.2"
