[package]
name = "staratlas-points"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []

[dependencies]
anchor-gen = "0.3"
anchor-lang = "0.29"
